### PR TITLE
Restrict install to darwin based OSes like Mac OS

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by s524797336** [comment]
I don't think this is a good idea. this package dependence **noble** which can use in all OSes and this package check if OS is Mac OS, otherwise use **noble**, so if a multi platform project use this package, it need install this package on all platform, not only Mac OS

**Comment by geovie** [comment]
This is already handled. See #8 for the rationale why.

Thanks!

**Comment by ghost** [comment]
ah, guess I'll have to keep using this branch anyways. I'm using it as a dependency of my own "maintained" fork of noble. 

 @s524797336 : so i can't just install this one, since my noble has about 100 more commits in it

**Comment by geovie** [comment]
@jrobeson You can use the bindings with your own fork:
```javascript
const Noble = require('<your forked noble>/lib/noble');
const macBindings = require('noble-mac/lib/binding.js');
var noble = new Noble(macBindings);
```

**Comment by ghost** [comment]
yeah, but I also had to make a peerdependency as well, so it wouldn't try to also install multiple copies of noble and try to also build xpc-connection and bluetooth-hci-socket again

**Comment by ghost** [comment]
As you can see, it's just like any other binding https://github.com/jrobeson/noble/blob/refactor/lib/resolve-bindings.ts#L10

**Pull request closed without merging**
